// vendor-core.js — copy the pure plasticityCore into the Worker as an ES module.
//
// The Worker runs on the Cloudflare Workers runtime (ES modules), while the app
// uses CommonJS. plasticityCore is intentionally dependency-free, so vendoring
// is just: copy the source and swap the `module.exports = {...}` tail for an
// `export { ... }`. Run this whenever the core changes to re-sync the copy.
//
//   node cloudflare/scripts/vendor-core.js
//
// Output: cloudflare/src/plasticityCore.mjs  (do not edit by hand — generated)

const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..', '..', 'src', 'core', 'plasticityCore.js');
const OUT = path.join(__dirname, '..', 'src', 'plasticityCore.mjs');

let code = fs.readFileSync(SRC, 'utf8');

// Replace the CommonJS export block with named ESM exports. The core's export
// is `module.exports = { name, name, ... };` — capture the names and emit
// `export { name, name, ... };`. (The functions/consts above are unchanged.)
const m = code.match(/module\.exports\s*=\s*\{([\s\S]*?)\};?\s*$/);
if (!m) {
  process.stderr.write('vendor-core: could not find module.exports block in plasticityCore.js\n');
  process.exit(1);
}
// Strip comments + whitespace from the captured names, keep identifiers only.
const names = m[1]
  .split(',')
  .map((s) => s.replace(/\/\/.*$/gm, '').trim())
  .filter((s) => /^[A-Za-z_$][\w$]*$/.test(s));

const banner = '// GENERATED by cloudflare/scripts/vendor-core.cjs from '
  + 'src/core/plasticityCore.js — do not edit by hand.\n'
  + '// Re-run `node cloudflare/scripts/vendor-core.cjs` after changing the core.\n\n';

const esm = banner
  + code.slice(0, m.index)            // everything before module.exports
  + `export {\n  ${names.join(',\n  ')},\n};\n`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, esm, 'utf8');
process.stdout.write(`Vendored ${names.length} exports → ${path.relative(process.cwd(), OUT)}\n`);

// Also vendor the viewer HTML in FETCH mode (no embedded data — the Worker's
// page calls /api/graph). Reuses the shared, DB-free viewer template so the
// deployed page and the local standalone share one source.
const { renderHtml } = require(path.join(__dirname, '..', '..', 'research', 'viewer-template.js'));
const HTML_OUT = path.join(__dirname, '..', 'src', 'viewer.html');
const html = renderHtml({ nodes: [], edges: [], meta: { nodeCount: 0, edgeCount: 0 } }, {
  embed: false, apiPath: '/api/graph',
});
fs.writeFileSync(HTML_OUT, html, 'utf8');
process.stdout.write(`Vendored viewer (fetch mode) → ${path.relative(process.cwd(), HTML_OUT)}\n`);
